### ISSUE TITLE
Crashes during initiall install

### ISSUE THREAD

**Issue by specimen151** [NetCoreTemplates/vuetify-spa#3]
`x new vuetify-spa CeeNineteen` crashes:
```

> vue-cli-service build


-  Building for production...
Starting type checking and linting service...
Using 1 worker with 2048MB memory limit
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

  `@babel/polyfill` is deprecated. Please, use required parts of `core-js`
  and `regenerator-runtime/runtime` separately
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
 ERROR  Error: No module factory available for dependency type: CssDependency
Error: No module factory available for dependency type: CssDependency
    at addDependency (C:\Programming\CovidOffice\CeeNineteen\CeeNineteen\node_modules\webpack\lib\Compilation.js:800:12)
    at iterationOfArrayCallback (C:\Programming\CovidOffice\CeeNineteen\CeeNineteen\node_modules\webpack\lib\Compilation.js:208:3)
    at addDependenciesBlock (C:\Programming\CovidOffice\CeeNineteen\CeeNineteen\node_modules\webpack\lib\Compilation.js:816:5)
    at Compilation.processModuleDependencies (C:\Programming\CovidOffice\CeeNineteen\CeeNineteen\node_modules\webpack\lib\Compilation.js:827:4)
    at afterBuild (C:\Programming\CovidOffice\CeeNineteen\CeeNineteen\node_modules\webpack\lib\Compilation.js:954:15)
    at C:\Programming\CovidOffice\CeeNineteen\CeeNineteen\node_modules\webpack\lib\Compilation.js:998:11
    at callback (C:\Programming\CovidOffice\CeeNineteen\CeeNineteen\node_modules\webpack\lib\Compilation.js:734:5)
    at C:\Programming\CovidOffice\CeeNineteen\CeeNineteen\node_modules\webpack\lib\Compilation.js:782:12
    at handleParseResult (C:\Programming\CovidOffice\CeeNineteen\CeeNineteen\node_modules\webpack\lib\NormalModule.js:478:12)
    at C:\Programming\CovidOffice\CeeNineteen\CeeNineteen\node_modules\webpack\lib\NormalModule.js:500:6
    at C:\Programming\CovidOffice\CeeNineteen\CeeNineteen\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Programming\CovidOffice\CeeNineteen\CeeNineteen\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Programming\CovidOffice\CeeNineteen\CeeNineteen\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at C:\Programming\CovidOffice\CeeNineteen\CeeNineteen\node_modules\loader-runner\lib\LoaderRunner.js:186:6
    at context.callback (C:\Programming\CovidOffice\CeeNineteen\CeeNineteen\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\programming\CovidOffice\CeeNineteen\CeeNineteen\node_modules\mini-css-extract-plugin\dist\loader.js:199:12
    at C:\Programming\CovidOffice\CeeNineteen\CeeNineteen\node_modules\webpack\lib\Compiler.js:343:11
    at C:\Programming\CovidOffice\CeeNineteen\CeeNineteen\node_modules\webpack\lib\Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Programming\CovidOffice\CeeNineteen\CeeNineteen\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:13:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Programming\CovidOffice\CeeNineteen\CeeNineteen\node_modules\tapable\lib\Hook    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Programming\CovidOffice\CeeNineteen\CeeNineteen\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:4:1)
npm ERR! errno 1
npm ERR! cee-nineteen@0.1.0 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cee-nineteen@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxxx\AppData\Roaming\npm-cache\_logs\2020-12-07T18_13_31_680Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cee-nineteen@0.1.0 postinstall: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cee-nineteen@0.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxxx\AppData\Roaming\npm-cache\_logs\2020-12-07T18_13_31_828Z-debug.log

```

**Comment by specimen151** [comment]
Found the problem.
I was running on windows on path c:\programming\something when I got the error.
Actually the folder is called Programming with capital P. Windows doesn't separate, but sometimes this leads to problems anyway. So just cd \Programming\something made it work.

**Comment by mythz** [comment]
Can't repro the issue locally, which builds & runs without error:

```
added 2155 packages from 1162 contributors and audited 2161 packages in 67.472s

42 packages are looking for funding
  run `npm fund` for details

found 44037 vulnerabilities (43984 low, 53 high)
  run `npm audit fix` to fix them, or `npm audit` for details



CeeNineteen vuetify-spa project created.
```

    $ dotnet run

![image](https://user-images.githubusercontent.com/89361/101389886-06638980-38fd-11eb-8303-058902d42aff.png)

From this error message you may have a non standard node installation:
https://github.com/webpack-contrib/mini-css-extract-plugin/issues/493

I've updated the templates npm deps in [this commit](https://github.com/NetCoreTemplates/vuetify-spa/commit/6a898a613a2b192f9e2a24eb8caeaa2b9cc8ac10) in case it's an issue fixed in the latest version of one of its deps, so if you create the template again it will be using the latest version of its npm deps:

    $ x new vuetify-spa CeeNineteen

**Comment by specimen151** [comment]
Sorry, but I closed this already with a comment on what caused the error.
Basically, on Windows, I have a folder C:\Programming
but then I cd'ed into ut with "cd \programming", which is no problem. But
then Windows will remember that I'm in C:\programming (with lowercase p),
which is the same folder, but still some tools behave differently. When I
did "cd \Programming" (really the same folder) then it works.

**Comment by mythz** [comment]
ok no worries, but I had already tried to repro the issue & updated all the deps before you had closed the issue. At least the latest template is using the latest dependencies.
